config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: { sessions: 'users/sessions' }

  resources :self_registrations, only: %i[create new] do
    collection do
      get 'success'
      get 'terms_of_use'
    end
  end

  root to: 'kids#index'
  resources :admins
  resources :documents
  resources :mentors do
    member do
      get 'edit_schedules'
      patch 'update_schedules'
      get 'disable_no_kids_reminder'
    end
  end
  resources :kids do
    resources :journals do
      resources :comments, only: %w[new create edit update]
    end
    resources :reviews
    resources :first_year_assessments
    resources :termination_assessments
    member do
      get 'edit_schedules'
      get 'show_kid_mentors_schedules'
      patch 'show_kid_mentors_schedules'
      patch 'update_schedules'
    end
  end
  resources :kid_mentor_relations do
    delete :destroy_all, on: :collection
  end
  resources :available_kids
  resources :schedules
  resources :schools
  resources :reminders
  resources :teachers
  resources :principals
  resource :site
  resources :substitutions do
    member do
      put 'inactivate'
    end
  end
  resources :mentor_matchings do
    member do
      put :accept
      put :decline
      put :confirm
    end
  end

  get '/lehrpersonen', to: redirect('/self_registrations/new?type=teacher')
  get '/mentoren', to: redirect('/self_registrations/new?type=mentor')

  get '/exception_test' => 'exception_test#error'
end

app/models/kid.rb
class Kid < ApplicationRecord
  include HasCoordinates
  include ActionView::Helpers::TextHelper

  default_scope { order(:name, :prename) }

  scope :active, -> { where(inactive: false) }
  scope :with_mentor, -> { where.not(mentor_id: nil) }

  belongs_to :mentor, optional: true
  belongs_to :secondary_mentor, class_name: 'Mentor', optional: true
  belongs_to :teacher, optional: true
  belongs_to :secondary_teacher, class_name: 'Teacher', optional: true
  belongs_to :third_teacher, class_name: 'Teacher', optional: true
  belongs_to :admin, optional: true
  belongs_to :school, optional: true

  has_many :journals, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :first_year_assessments, dependent: :destroy
  has_many :termination_assessments, dependent: :destroy
  has_many :reminders, dependent: :destroy
  has_many :schedules, as: :person, dependent: :destroy
  has_many :substitutions, dependent: :destroy
  has_many :relation_logs, dependent: :nullify
  has_many :mentor_matchings, dependent: :destroy

  GOALS_1 = %i[goal_3 goal_4 goal_5 goal_6 goal_7
               goal_8 goal_9 goal_10 goal_11 goal_12 goal_13 goal_14
               goal_15 goal_16 goal_17 goal_18 goal_19 goal_20 goal_21
               goal_22 goal_23 goal_24].freeze
  GOALS_1_MAX = 4

  GOALS_2 = %i[goal_25 goal_26 goal_27 goal_28 goal_29 goal_30 goal_31
               goal_32 goal_33 goal_34 goal_35].freeze
  GOALS_2_MAX = 2

  accepts_nested_attributes_for :journals, :reviews, :schedules

  validates :name, :prename, presence: true

  validates :sex, :grade, :language,
            :address, :city, :parent, :phone,
            :simplified_schedule, presence: { if: :validate_public_signup_fields? }

  validates :meeting_day, numericality: { only_integer: true, allow_blank: true,
                                          greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

  # the html5 date submit allows two letter dates (e.g. '21') and translates them to wrong years (like '0021')
  validates_date :dob, :exit_at, :checked_at, :coached_at, after: '2001-01-01', allow_blank: true

  # validate that enough goals were given in each group
  validate do |kid|
    goals_1_count = GOALS_1.count { |g| kid[g].present? }
    if kid[:goal_1].blank? && 0 == goals_1_count
      GOALS_1.each { |g| errors.add g, :invalid, message: '' }
      errors.add :goal_1, :invalid, message: 'Bitte geben Sie mindestens einen fachlichen Förderbereich an'
      # this code would hard constrain goals to maximum. at the moment it is only a soft constraint
      # elsif GOALS_1_MAX < goals_1_count
      # GOALS_1.each { |g| errors.add g, :invalid, message: '' }
      # errors.add :goal_1, :invalid, message: "Bitte geben Sie maximal #{GOALS_1_MAX}  Fachliche Förderbereiche an"
    end

    goals_2_count = GOALS_2.count { |g| kid[g].present? }
    if kid[:goal_2].blank? && 0 == goals_2_count
      GOALS_2.each { |g| errors.add g, :invalid, message: '' }
      errors.add :goal_2, :invalid, message: 'Bitte geben Sie mindestens einen überfachlichen Förderbereich an'
      # this code would hard constrain goals to maximum. at the moment it is only a soft constraint
      # elsif GOALS_2_MAX < goals_2_count
      # GOALS_2.each { |g| errors.add g, :invalid, message: '' }
      # errors.add :goal_2, :invalid, message: "Bitte geben Sie maximal #{GOALS_2_MAX} Überfachliche Förderbereich an"
    end
  end

  after_validation :track_goal_updates
  before_destroy :release_relations
  after_save :release_relations, if: :inactive?
  after_save :track_relations

  # takes the given time argument (or Time.now) and calculates the
  # date and time for that weeks meeting
  def calculate_meeting_time(time = Time.now)
    meeting_day = self.meeting_day
    meeting_start_at = self.meeting_start_at

    if meeting_day.blank? || meeting_start_at.blank?
      # saturday evening
      meeting_day = 6
      meeting_start_at = Time.zone.parse('18:00')
    end
    time = time.monday
    time += (meeting_day - 1).days
    time += meeting_start_at.hour.hours
    time += meeting_start_at.min.minutes
    time
  end

  # tries to retrieve the journal entry for the week given by time
  def journal_entry_for_week(time = Time.now)
    time = calculate_meeting_time(time)
    return nil if time.nil?

    journals.find_by(week: time.strftime('%U').to_i, year: time.year)
  end

  # tries to retrieve the reminder for the week given by time
  def reminder_entry_for_week(time = Time.now)
    time = calculate_meeting_time(time)
    return nil if time.nil?

    reminders.find_by(week: time.strftime('%U').to_i, year: time.year)
  end

  # checks wether a journal entry is already due for the week given by time
  def journal_entry_due?(time = Time.now)
    meeting_time = calculate_meeting_time(time)
    return false if meeting_time.nil?

    (meeting_time + 1.day) < time
  end

  # when controlling reminders it is useful to know the date of the most recent
  # journal entry made for the associated kid
  def last_journal_entry
    journals.order('held_at DESC').first
  end

  # shows when last schedule relation entry was edited
  def schedules_updated_at
    Schedule.schedules_updated_at(self)
  end

  def display_name
    return 'Neuer Eintrag' if new_record?

    [name, prename].reject(&:blank?).join(', ')
  end

  def human_goal
    text_format(goal)
  end

  def human_goal_1
    text_format(goal_1)
  end

  def human_goal_2
    text_format(goal_2)
  end

  def human_simplified_schedule
    text_format(simplified_schedule)
  end

  def human_note
    text_format(note)
  end

  def human_todo
    text_format(todo)
  end

  def human_abnormality
    text_format(abnormality)
  end

  def human_abnormality_criticality
    return '' unless abnormality_criticality

    I18n.t(abnormality_criticality, scope: 'kids.criticality')
  end

  def human_sex
    { 'm' => 'männlich', 'f' => 'weiblich', 'd' => 'divers' }[sex]
  end

  def human_meeting_day
    return nil if meeting_day.nil?

    I18n.t('date.day_names')[meeting_day]
  end

  def human_meeting_start_at
    return nil if meeting_start_at.nil?

    I18n.l(meeting_start_at, format: :time)
  end

  def human_exit_kind
    return '' if exit_kind.blank?

    I18n.t(exit_kind, scope: 'exit_kind')
  end

  def parent_country_name
    return '' if parent_country.blank?

    c = ISO3166::Country[parent_country]
    c.translations[I18n.locale.to_s] || c.name
  end

  # checks if kid is not already assigned to a mentor
  def match_available?(mentor)
    # preloaded
    mentor_matchings.to_a.select do |mentor_matching|
      !mentor_matching.new_record? && mentor_matching.mentor_id == mentor.id
    end.count == 0
  end

  def mentor_matching_for(mentor)
    # preloaded
    mentor_matchings.to_a.detect { |mentor_matching| mentor_matching.mentor_id == mentor.id }
  end

  protected

  def release_relations
    # Use update_columns to bypass callbacks and directly update the database
    # This prevents infinite loops since we're in an after_save callback
    update_columns(
      mentor_id: nil,
      secondary_mentor_id: nil,
      teacher_id: nil,
      secondary_teacher_id: nil,
      third_teacher_id: nil,
      admin_id: nil
    )
  end

  def track_relations
    track_relation(:mentor)
    track_relation(:secondary_mentor)
    track_relation(:teacher)
    track_relation(:secondary_teacher)
    track_relation(:third_teacher)
    track_relation(:admin)
  end

  # create a relation log for the given field if it has changed
  def track_relation(field)
    changed = saved_change_to_attribute?("#{field}_id")
    current_id = send("#{field}_id")
    previous_id = attribute_before_last_save("#{field}_id")
    if changed && previous_id
      relation_logs.create!(user_id: previous_id,
                            role: field,
                            end_at: Time.now)
    end
    return unless changed && current_id

    relation_logs.create!(user_id: send("#{field}_id"),
                          role: field,
                          start_at: Time.now)
  end

  # on instances with public signup configured stronger validations are applied
  def validate_public_signup_fields?
    Site.load.public_signups_active?
  end

  # track all changes of the goal freetext and checkbox fields
  # in one field
  def track_goal_updates
    return unless changed.any? { |k| k.start_with?('goal_') }

    self.goals_updated_at = Time.now
  end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  respond_to :html, :json

  load_and_authorize_resource
  include CrudActions
  include ManageSchedules # edit_schedules & update_schedules

  before_action :cancan_prototypes, only: [:show]
  before_action :assign_current_teacher, only: [:create]
  before_action :prepare_substitution
  before_action :intercept_school_id
  before_action :load_and_constrain_schools, except: %i[index show show_kid_mentors_schedules]
  after_action :track_creation_relation, only: [:create]

  def index
    # for admin users, the kids view may be filtered. these code is only
    # executed for admins since else we would have to take care that no other
    # user overwrites its filter constraints by adding a certain query parameter
    # here
    if current_user.is_a?(Admin) || current_user.is_a?(Principal)
      # a prototyped kid is submitted with each index query. if the prototype
      # is not present, it is built here with default values
      # build a where condition out of all parameters supplied for kid
      params[:kid] ||= {}
      params[:kid][:inactive] = '0' if params[:kid][:inactive].nil?
      @kids = @kids.where(kid_params.to_h.delete_if { |key, val| !Kid.column_names.include?(key.to_s) || val.blank? })
      # reorder the kids according to the supplied parameter

      @kids = @kids.reorder(params['order_by']) if params['order_by'] && valid_order_by?(Kid, params['order_by'])
      # provide a prototype for the filter form
      @kid = Kid.new(kid_params)
    end

    return render xlsx: 'index' if current_user.is_a?(Admin) && 'xlsx' == params[:format]

    respond_with @kids
  end

  # update may be called from different sources
  # - normal rails edit form
  # - react component on show_kid_mentors_schedules
  # - react component on show_kid_mentors_schedules in substitution workflow
  def update
    unless @kid.update(kid_params)
      # validation failed
      return render :edit
    end

    # normal call - not through substitution workflow
    return respond_with(@kid) unless @substitution

    # call included substitution_id: sync substitution information
    @substitution.update!(secondary_mentor: @kid.secondary_mentor)
    redirect_to substitution_url(@substitution)
  end

  def show_kid_mentors_schedules
    # prepare substitution json
    @kid_mentor_schedules_data = Jbuilder.new do |json|
      json.mentors do
        Mentor.active.each do |mentor|
          json.set! mentor.id do
            json.id mentor.id
            json.prename mentor.prename
            json.name mentor.name
            json.sex mentor.sex
            json.ects mentor.ects
            json.kids mentor.kids, :id, :name, :prename
            json.secondary_kids mentor.secondary_kids, :id, :name, :prename
            json.schools mentor.schools.ids
            json.schedules create_schedules_nested_set mentor.schedules
          end
        end
      end
      json.kid do
        json.id @kid.id
        json.prename @kid.prename
        json.name @kid.name
        json.mentor_id @kid.mentor_id
        json.meeting_start_at get_meeting_start_time
        json.meeting_day get_meeting_day
        json.secondary_mentor_id @kid.secondary_mentor_id
        json.schedules create_schedules_nested_set @kid.schedules
      end
      json.schools School.all, :id, :display_name
    end.attributes!
  end

  protected

  def get_meeting_start_time
    return nil if @kid.meeting_start_at.blank?

    @kid.meeting_start_at.strftime('%H:%M')
  end

  def get_meeting_day
    return nil if @kid.meeting_day.blank?

    @kid.meeting_day
  end

  # when the user working on the kid is a teacher, it get's
  # assigned as the first teacher of the kid in creation case
  def assign_current_teacher
    return true unless current_user.is_a?(Teacher)
    return true if @kid.teacher.present?

    return if @kid.secondary_teacher == current_user || @kid.third_teacher == current_user

    @kid.teacher ||= current_user
  end

  def track_creation_relation
    return true unless @kid.persisted?

    @kid.relation_logs.create(user_id: current_user.id,
                              role: 'creator',
                              start_at: Time.now)
  end

  # prototypes to check abilities in menu
  def cancan_prototypes
    @cancan_journal = Journal.new(kid: @kid)
    @cancan_review = Review.new(kid: @kid)
    @cancan_journal.mentor = current_user if current_user.is_a?(Mentor)
    @cancan_first_year_assessment = FirstYearAssessment.new(kid: @kid)
    @cancan_termination_assessment = TerminationAssessment.new(kid: @kid)
  end

  private

  def kid_params
    if params[:kid].present?
      params.require(:kid).permit(
        :name, :prename, :sex, :dob, :grade, :language, :parent_country, :parent, :address,
        :city, :phone, :translator, :note, :school_id,
        :goal_1, :goal_2, :goal_3, :goal_4, :goal_5, :goal_6, :goal_7, :goal_8, :goal_9, :goal_10,
        :goal_11, :goal_12, :goal_13, :goal_14, :goal_15, :goal_16, :goal_17, :goal_18, :goal_19,
        :goal_20, :goal_21, :goal_22, :goal_23, :goal_24, :goal_25, :goal_26, :goal_27, :goal_28,
        :goal_29, :goal_30, :goal_31, :goal_32, :goal_33, :goal_34, :goal_35,
        :simplified_schedule,
        :meeting_day, :meeting_start_at, :teacher_id, :secondary_teacher_id,
        :third_teacher_id, :mentor_id, :secondary_mentor_id, :secondary_active, :admin_id, :term,
        :exit, :exit_reason, :exit_kind, :exit_at, :checked_at,
        :coached_at, :abnormality,
        :abnormality_criticality, :todo, :inactive,
        schedules_attributes: %i[day hour minute]
      )
    else
      {}
    end
  end

  # In the react-component, we need the schedules as some kind of "nested-set"
  # It is a hash where an entry set[day]["hour:minute"] is true, if that day and
  # time occurs in the array. Otherwise this key does not exist.
  def create_schedules_nested_set(schedules_array)
    schedules_set = Hash.new { |h, k| h[k] = Hash.new { |h, k| h[k] = {} } }
    schedules_by_day = schedules_array.group_by { |s| s.day }
    schedules_by_day.each do |day, times|
      times.each do |time|
        key = time.hour.to_s.rjust(2, '0') + ':' + time.minute.to_s.rjust(2, '0')
        schedules_set[day][key] = true
      end
    end
    schedules_set
  end

  # this form may be reached from substitutions, this is indicated
  # by a parameter substitution_id
  def prepare_substitution
    return unless params[:substitution_id].present?

    @substitution = Substitution.find(params[:substitution_id])
  end

  def load_and_constrain_schools
    case current_user
    when Teacher
      @schools = [current_user.school]
      @schools_include_blank = false
    when Principal
      @schools = current_user.schools
      @schools_include_blank = false
    when Admin
      @schools = School.by_kind(:kid)
      @schools_include_blank = true
    else
      raise SecurityError.new("User #{current_user.id}")
    end
  end

  # do not let teachers and principals change the school id of foreign
  # objects not to let kids be assigned to other entities
  def intercept_school_id
    return if current_user.is_a?(Admin)

    school_id = params[:kid] && params[:kid][:school_id]
    return unless school_id.present?

    valid_school_ids = []
    if current_user.is_a?(Principal)
      valid_school_ids = current_user.schools.map(&:id)
    elsif current_user.is_a?(Teacher)
      valid_school_ids = [current_user.school_id]
    end
    return if valid_school_ids.map(&:to_s).include?(school_id)

    raise SecurityError.new("User #{current_user.id} not allowed to change school_id to #{school_id}")
  end
end

app/views/kids/_form.html.haml
= simple_form_for @kid do |form|

  = form.input :name, required: true
  = form.input :prename, required: true
  = form.input :sex, :collection => sex_collection, required: true
  = form.input :dob, as: :date, html5: true
  .form-group.select.required.kid_grade
    %label.col-sm-3.control-label.select.required
      = Kid.human_attribute_name(:grade)
      %br
      %em (bei Einstieg Future Kids)
    .col-sm-9
      = form.select :grade, grade_collection, { include_blank: true }, { class: 'form-control select required' }

  = form.input :language, required: true
  = form.input :parent_country, priority: ["AL", "TR", "LK", "XK", "ES", "PT"], :include_blank => true, locale: 'de'

  = form.input :parent, required: true
  = form.input :address, required: true
  = form.input :city, required: true
  = form.input :phone, required: true
  = form.input :translator
  = form.input :note
  = form.association :school, collection: @schools, include_blank: @schools_include_blank

  %h2
    Fachliche Förderbereiche
    %em="- mindestens eines, maximal #{Kid::GOALS_1_MAX}"
  - if @kid.errors[:goal_1].any?
    %h3.has-error
      %span.help-block= @kid.errors[:goal_1].try(:first)
  %h3 Deutsch
  =form_subtitle("Hören")
  = form.input :goal_3
  = form.input :goal_4
  = form.input :goal_5
  =form_subtitle("Lesen")
  = form.input :goal_6
  = form.input :goal_7
  = form.input :goal_8
  =form_subtitle("Sprechen")
  = form.input :goal_9
  = form.input :goal_10
  =form_subtitle("Schreiben")
  = form.input :goal_11
  = form.input :goal_12
  = form.input :goal_13
  =form_subtitle("Sprache im Fokus (Grammatik und Rechtschreibung)")
  = form.input :goal_14
  = form.input :goal_15

  %h3 Mathematik
  = form.input :goal_16
  =form_subtitle("Zahl und Variable")
  = form.input :goal_17
  = form.input :goal_18
  = form.input :goal_19
  = form.input :goal_20
  =form_subtitle("Form und Raum")
  = form.input :goal_21
  = form.input :goal_22
  =form_subtitle("Grössen")
  = form.input :goal_23
  = form.input :goal_24
  = form.input :goal_1

  %h2
    Überfachliche Förderbereiche
    %em="- mindestens eines, maximal #{Kid::GOALS_2_MAX}"
  - if @kid.errors[:goal_2].any?
    %h3.has-error
      %span.help-block= @kid.errors[:goal_2].try(:first)
  =form_subtitle("Personale Förderbereiche")
  = form.input :goal_25
  = form.input :goal_26
  = form.input :goal_27
  = form.input :goal_28
  = form.input :goal_29
  = form.input :goal_30
  = form.input :goal_31
  =form_subtitle("Methodische Förderbereiche")
  = form.input :goal_32
  = form.input :goal_33
  = form.input :goal_34
  = form.input :goal_35
  = form.input :goal_2


  %h2 Allgemeine Informationen
  - unless @site.kids_schedule_hourly
    %label.string.col-sm-3.control-label
    .col-sm-9
      %p Bitte mehrere Zeitfenster angeben, in denen das Kind Zeit für das Mentoring hat.
    = form.input :simplified_schedule, required: true
  - if current_user.is_a?(Admin)
    = form.input :meeting_day, :collection => wday_collection
    = form.input :meeting_start_at, :as => :string, input_html: { value: @kid.human_meeting_start_at, autocomplete: 'off' }
  -# this form is accessible by admins and teachers. teachers can only set the
  -# the secondary_mentor and ara automatically assigned as first mentor for any kid
  -# they are working on
  - if current_user.is_a?(Admin)
    = form.association :teacher, :collection => Teacher.active
    = form.association :secondary_teacher, :collection => Teacher.active
    = form.association :third_teacher, :collection => Teacher.active
    = form.association :mentor, :collection => Mentor.active
    = form.association :secondary_mentor, :collection => Mentor.active
    = form.input :secondary_active
  - if current_user.is_a?(Admin) && @site.feature_coach?
    = form.input :admin_id, :collection => Admin.active

  - if current_user.is_a?(Admin)
    %h2#internal Projektinterne Informationen
    = form.input :term, :collection => term_collection
    = form.input :exit, :collection => term_collection
    = form.input :exit_reason, :collection => exit_reason_collection
    = form.input :exit_kind, :collection => exit_kind_collection
    = form.input :exit_at, as: :date, html5: true
    = form.input :checked_at, as: :date, html5: true
    - if @site.feature_coach?
      = form.input :coached_at, as: :date, html5: true
    = form.input :abnormality
    = form.input :abnormality_criticality, :collection => criticality_collection
    = form.input :todo
    %a(name='todo')
    = form.input :inactive

  .col-sm-offset-3.col-sm-9
    = form.button :submit

app/views/kids/_subnav.html.haml
- content_for :sidebar do

  .panel.panel-default
    .panel-heading
      %h4.panel-title(data-toggle="collapse" data-target="#collapseJournals")
        Lernjournale
        %span.badge.pull-right=resource.journals.size
    #collapseJournals.collapse.list-group.kidanchors
      - resource.journals.each do |journal|
        .list-group-item
          = link_to journal.display_name, :anchor => dom_id(journal)

  - if resource.mentor == current_user || current_user.is_a?(Admin)
    .panel.panel-default
      .panel-heading
        %h4.panel-title(data-toggle="collapse" data-target="#collapseReviews")
          Gespräche
          %span.badge.pull-right=resource.reviews.size
      #collapseReviews.collapse.list-group.kidanchors
        - resource.reviews.each do |review|
          .list-group-item
            = link_to review.display_name, :anchor => dom_id(review)

app/views/kids/edit.html.haml
-# contextual links cannot display / undisplay links based on cancan parameters but only based on the models class.
-# since teachers can only be destroyed when they are inactive this leads to wrong displays if the delete menu
-# item, so we have to generate the menu explicitly
- content_for :contextual_links do
  .list-group
    = contextual_link_to :show, @kid
    - if can?(:destroy, @kid)
      = contextual_link_to :destroy, @kid
    = contextual_link_to :index

= boot_page_title

= render 'form'

app/views/kids/edit_schedules.html.haml
= render 'schedules/table', resource: @kid

app/views/kids/index.html.haml
- content_for :contextual_links do
  = contextual_links do
    - if current_user.is_a?(Admin)
      = contextual_link_to :xlsx, url_for(params.permit!.merge(format: 'xlsx'))

- content_for :sidebar do
  = form_for :kid, :url => { :action => 'index' }, :html => { :method => :get, :class => 'filter' } do |f|

    - if current_user.is_a?(Admin)
      .form-group
        %label= Kid.human_attribute_name(:term)
        = f.select :term, term_collection, { :include_blank => true }, class: 'form-control'
      .form-group
        %label= Kid.human_attribute_name(:exit)
        = f.select :exit, term_collection, { :include_blank => true }, class: 'form-control'
      .form-group
        %label= Kid.human_attribute_name(:school)
        = f.select :school_id, school_collection_by_kind(:kid), { :include_blank => true }, class: 'form-control'
      - if @site.feature_coach?
        .form-group
          %label Pädagogischer Coach
          = f.select :admin_id, admin_collection, { :include_blank => true }, class: 'form-control'
      .form-group
        %label Übersetzer
        = f.select :translator, boolean_collection, { include_blank: true }, class: 'form-control'
      .form-group
        %label= Kid.human_attribute_name(:meeting_day)
        = f.select :meeting_day, wday_collection, { :include_blank => true }, class: 'form-control'


    - if current_user.is_a?(Admin) || current_user.is_a?(Principal)
      .form-group
        %label Klasse
        = f.select :grade, grade_collection, { :include_blank => true }, class: 'form-control'

    - if current_user.is_a?(Admin) or current_user.is_a?(Principal)
      .checkbox
        %label
          = f.check_box :inactive
          %p
            %b Inaktive

    .form-group
      %label Ordnen nach
      = select_tag 'order_by', order_by_collection_for_kids(params[:order_by]), class: 'form-control'
    .form-group
      = f.submit 'Suchen', class: 'btn btn-xs btn-success'

      - if current_user.is_a?(Admin) or current_user.is_a?(Principal)
        = link_to 'Filter aufheben', kids_path, class: 'btn btn-xs'

= boot_page_title do
  = @kids.count if current_user.is_a?(Admin) or current_user.is_a?(Principal)
  Sch&uuml;ler/innen

%p
  = page_description
%p &nbsp;

%table.table.table-striped.table-condensed.table-hover
  %tr
    %th Name
    - if current_user.is_a?(Admin) or current_user.is_a?(Principal)
      %th Eintritt
    - if current_user.is_a?(Admin)
      %th Letztes Kontrolldatum
      - if @site.feature_coach?
        %th Letztes pädagogisches Coaching
      %th Pendenzen
    %th Mentor/in
    - if @site.feature_coach?
      %th Pädagogischer Coach
  - @kids.each do |kid|
    %tr
      %td= link_to kid.display_name, kid
      -if current_user.is_a?(Admin) or current_user.is_a?(Principal)
        %td
          = kid.created_at ? I18n.l(kid.created_at.to_date) : '-'
      -if current_user.is_a?(Admin)
        %td
          = kid.checked_at ? I18n.l(kid.checked_at.to_date) : '-'
        - if @site.feature_coach?
          %td
            = kid.coached_at ? I18n.l(kid.coached_at.to_date) : '-'
        %td
          -if current_user.is_a?(Admin) && kid.todo.present?
            %a.todotoggle.btn.btn-xs{data: { content: kid.human_todo}, href:  edit_kid_path(kid, :anchor => 'todo') }
              Pendenz
              %span.glyphicon.glyphicon-info-sign
      %td
        = can_link_to(kid.mentor) if kid.mentor.present?
      - if @site.feature_coach?
        %td
          = can_link_to(kid.admin) if kid.admin.present?


- if @kids.empty?
  Keine Kinder zugeordnet / erfasst.

app/views/kids/show.html.haml
= boot_page_title @kid.display_name

- content_for :contextual_links do
  .list-group
    - if can?(:edit, @kid)
      = contextual_link_to :edit, @kid
    - if can?(:destroy, @kid)
      = contextual_link_to :destroy, @kid
    - if can? :create, @cancan_journal
      = contextual_link_to :new_journal, new_kid_journal_path(@kid)
    - if can? :create, @cancan_review
      = contextual_link_to :new_review, new_kid_review_path(@kid)
    - if can? :create, @cancan_first_year_assessment
      = contextual_link_to :new_first_year_assessment, new_kid_first_year_assessment_path(@kid)
    - if can? :create, @cancan_termination_assessment
      = contextual_link_to :new_termination_assessment, new_kid_termination_assessment_path(@kid)
    - if @site.kids_schedule_hourly
      = contextual_link_to :edit_schedules
      = contextual_link_to :show_kid_mentors_schedules
    = contextual_link_to :index

= render "show"