config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: { sessions: 'users/sessions' }

  resources :self_registrations, only: %i[create new] do
    collection do
      get 'success'
      get 'terms_of_use'
    end
  end

  root to: 'kids#index'
  resources :admins
  resources :documents
  resources :mentors do
    member do
      get 'edit_schedules'
      patch 'update_schedules'
      get 'disable_no_kids_reminder'
    end
  end
  resources :kids do
    resources :journals do
      resources :comments, only: %w[new create edit update]
    end
    resources :reviews
    resources :first_year_assessments
    resources :termination_assessments
    member do
      get 'edit_schedules'
      get 'show_kid_mentors_schedules'
      patch 'show_kid_mentors_schedules'
      patch 'update_schedules'
    end
  end
  resources :kid_mentor_relations do
    delete :destroy_all, on: :collection
  end
  resources :available_kids
  resources :schedules
  resources :schools
  resources :reminders
  resources :teachers
  resources :principals
  resource :site
  resources :substitutions do
    member do
      put 'inactivate'
    end
  end
  resources :mentor_matchings do
    member do
      put :accept
      put :decline
      put :confirm
    end
  end

  get '/lehrpersonen', to: redirect('/self_registrations/new?type=teacher')
  get '/mentoren', to: redirect('/self_registrations/new?type=mentor')

  get '/exception_test' => 'exception_test#error'
end

app/views/admins/_form.html.haml
= simple_form_for @admin do |form|
  = form.input :name
  = form.input :prename
  = form.input :email
  = form.input :phone
  = form.input :password
  = form.input :password_confirmation
  = form.input :address
  = form.input :city

  -if current_user.is_a?(Admin)
    = form.input :note
    = form.input :inactive

  .col-sm-offset-3.col-sm-9
    = form.button :submit

app/views/admins/_list.html.haml
- content_for :sidebar do
  -if current_user.is_a?(Admin)
    %li
      %h4 Filterkriterium f&uuml;r Mentoren
      = form_for :admin, :url => { :action => 'index' }, :html => { :method => :get, :class => 'filter' } do |f|
        .checkbox
          %label
            = f.check_box :inactive
            %p Inaktive

        .form-group
          = f.submit 'Filter anwenden', class: 'btn btn-xs btn-success'
          = link_to 'Filter aufheben', collection_path, class: 'btn btn-xs btn-danger'

%h2
  = collection.count if current_user.is_a?(Admin)
  Administratoren

= render '/users/list'

app/views/admins/_show.html.haml
= show_for @admin do |show|
  = show.attribute :name
  = show.attribute :prename
  = show.attribute(:email) { mail_to @admin.email }
  = show.attribute :phone
  = show.attribute :address
  = show.attribute :city

  -if current_user.is_a?(Admin) && @site.feature_coach?
    = show.attribute :note
    = show.association :coachings do |k|
      %li
        = "#{Kid.model_name.human}:"
        = can_link_to k
        = "(#{k.city})" if k.city.present?
        - if k.mentor.present?
          = "- #{Mentor.model_name.human}:"
          = can_link_to k.mentor if k.mentor.present?
    = show.attribute :inactive
    - if @admin.inactive?
      = show.attribute :inactive_at

    = render 'relation_logs/collection', resource: @admin

app/views/admins/index.html.haml
- content_for :sidebar do
  -if current_user.is_a?(Admin)
    = form_for :admin, :url => { :action => 'index' }, :html => { :method => :get, :class => 'filter' } do |f|
      .checkbox
        %label
          = f.check_box :inactive
          %p
            %b Inaktive

      .form-group
        = f.submit 'Filter anwenden', class: 'btn btn-xs btn-success'
        = link_to 'Filter aufheben', admins_path, class: 'btn btn-xs'

= boot_page_title do
  = @admins.count if current_user.is_a?(Admin)
  Administratoren

= render 'users/list', collection: @admins

app/views/admins/show.html.haml
%h2= resource.display_name

= show_for resource do |show|
  = show.attribute :name
  = show.attribute :prename
  = show.attribute(:email) { mail_to resource.email }
  = show.attribute :phone
  = show.attribute :todo

  -if current_user.is_a?(Admin)
    = show.association :coachings do |k|
      %li
        = can_link_to k
        = "(#{k.city})" if k.city.present?
    = show.attribute :inactive

    = render :partial => 'relation_logs/collection'