config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: { sessions: 'users/sessions' }

  resources :self_registrations, only: %i[create new] do
    collection do
      get 'success'
      get 'terms_of_use'
    end
  end

  root to: 'kids#index'
  resources :admins
  resources :documents
  resources :mentors do
    member do
      get 'edit_schedules'
      patch 'update_schedules'
      get 'disable_no_kids_reminder'
    end
  end
  resources :kids do
    resources :journals do
      resources :comments, only: %w[new create edit update]
    end
    resources :reviews
    resources :first_year_assessments
    resources :termination_assessments
    member do
      get 'edit_schedules'
      get 'show_kid_mentors_schedules'
      patch 'show_kid_mentors_schedules'
      patch 'update_schedules'
    end
  end
  resources :kid_mentor_relations do
    delete :destroy_all, on: :collection
  end
  resources :available_kids
  resources :schedules
  resources :schools
  resources :reminders
  resources :teachers
  resources :principals
  resource :site
  resources :substitutions do
    member do
      put 'inactivate'
    end
  end
  resources :mentor_matchings do
    member do
      put :accept
      put :decline
      put :confirm
    end
  end

  get '/lehrpersonen', to: redirect('/self_registrations/new?type=teacher')
  get '/mentoren', to: redirect('/self_registrations/new?type=mentor')

  get '/exception_test' => 'exception_test#error'
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  # virtual attributes to support filter parameters
  attr_accessor :filter_by_school_id
  attr_accessor :filter_by_ects

  default_scope { order('held_at DESC, id') }
  scope :active, -> { where('reminders.acknowledged_at IS NULL') }

  belongs_to :mentor
  belongs_to :secondary_mentor, class_name: 'Mentor', optional: true
  belongs_to :kid

  validates :kid, presence: true

  # sends the reminder to the appropriate recipient
  def deliver_mail
    mail = Notifications.remind(self)
    mail.deliver_later
    update!(sent_at: Time.now)
  end

  # create a reminder for the given kid and the given time
  #
  # this method does no condition checks if the reminder is really needed from
  # the business point of view.
  #
  # method looks up when the meeting should have been held for the given kid
  # in the week of time and creates a reminder according to these settings
  def self.create_for(kid, time)
    Reminder.create! do |r|
      r.kid = kid
      r.mentor = kid.mentor
      r.secondary_mentor = kid.secondary_mentor
      r.held_at = kid.calculate_meeting_time(time)
      r.week = r.held_at.strftime('%U')
      r.year = r.held_at.year
      # the recipient of the reminder should be the active mentor
      r.recipient = if kid.secondary_active? && kid.secondary_mentor
                      kid.secondary_mentor.email
                    else
                      kid.mentor&.email
                    end
    end
  end

  # scans all kids and creates reminders for kids that meet the conditions
  #
  # typically called via cron once a day
  #
  # There are different rules which decide if reminders are created or not.
  # When you have to create reminders for development make sure that you
  # - have mentors assigned to kids
  # - kids have meeting days (best at start of week) and meeting time set
  # - not all journal entries or reminders are there
  # - you pass a parameter time that is a few days after the kids meeting day
  def self.conditionally_create_reminders(time = Time.now)
    logger.info("Beginning reminder run, reference Date #{time}")
    logger.flush

    reminders_created_count =
      Kid.all.find_each.count do |kid|
        conditionally_create_reminder_for_kid(time, kid)
      end

    # send out admin notification when reminders were created
    if reminders_created_count > 0
      # since this is run async from cron delivery can run instantly
      Notifications.reminders_created(reminders_created_count).deliver_now
    end

    logger.info(
      "Created #{reminders_created_count} reminders, reference Date #{time}"
    )
    logger.flush

    reminders_created_count
  rescue StandardError => e
    logger.error 'Exception during reminder run'
    logger.error e.message
    logger.error e.backtrace.join("\n")
    logger.flush
  end

  def self.conditionally_create_reminder_for_kid(time, kid)
    log_preamble = "[#{kid.id}] #{kid.display_name}: "

    logger.info(log_preamble + ' checking journal entries')
    logger.flush

    log_message =
      if !kid.journal_entry_due?(time)
        'no entry due'
      elsif kid.journal_entry_for_week(time)
        'journal entry present'
      elsif kid.reminder_entry_for_week(time)
        'reminder entry present'
      elsif kid.mentor.nil? && kid.secondary_mentor.nil?
        'no mentors set'
      else
        reminder = Reminder.create_for(kid, time)
        reminder_created = true
        "created reminder [#{reminder.id}]"
      end

    logger.info(log_preamble + log_message)
    logger.flush

    reminder_created
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  load_and_authorize_resource
  include CrudActions

  def index
    params[:reminder] ||= {}
    @reminders = @reminders.active

    last_selected_school = params[:reminder][:filter_by_school_id]
    if last_selected_school.present?
      @reminders = @reminders.joins(kid: [:school])
                             .where({ kids: { school_id: last_selected_school.to_i } })
    end
    params[:reminder][:filter_by_school_id] = last_selected_school

    last_selected_ects = params[:reminder][:filter_by_ects]
    if last_selected_ects.present?
      @reminders = @reminders.joins(:mentor)
                             .where({ mentor: { ects: last_selected_ects } })
    end
    params[:reminder][:filter_by_ects] = last_selected_ects

    @reminder = Reminder.new(reminder_params)
    respond_with @reminders
  end

  # update is used to trigger the mail delivery and to set the state
  # of the reminder to delivered. it will be displayed further on reminders
  # page until it is acknowledged (which is mapped t:fallback_locationo the destroy action)
  def update
    @reminder.deliver_mail # will also set sent_at flag

    respond_to do |format|
      format.js
      format.html do
        redirect_back fallback_location: reminders_url, notice: "Erinnerung wird zugestellt an #{@reminder.recipient}"
      end
    end
  end

  # destroy is used to acknowledge reminders
  #
  # there is only a soft delete for reminders so that we do not create
  # reminders for a certain week and mentor twice. acknowledged reminders
  # are not displayed anymore
  def destroy
    @reminder.update_attribute(:acknowledged_at, Time.now)
    respond_to do |format|
      format.js
      format.html { redirect_back fallback_location: reminders_url }
    end
  end

  private

  def reminder_params
    if params[:reminder].present?
      params.require(:reminder).permit(:filter_by_school_id, :filter_by_ects)
    else
      {}
    end
  end
end

app/views/reminders/destroy.js.erb
// When background submitted, the button receives the disabled flag
// After successful execution the whole row can be removed from the dom
$('#reminders_table button:disabled').closest('tr').remove();

app/views/reminders/index.html.haml
- content_for :sidebar do
  -if current_user.is_a?(Admin)
    = form_for :reminder, url: { action: 'index' }, html: { method: :get, class: 'filter' } do |f|
      .form-group
        %label= Kid.human_attribute_name(:school)
        = f.select :filter_by_school_id, school_collection, { include_blank: true }, class: 'form-control'
      .form-group
        %label=Mentor.human_attribute_name('ects')
        = f.select :filter_by_ects, ects_collection, { include_blank: true }, class: 'form-control'
      .form-group
        = f.submit 'Filter anwenden', class: 'btn btn-xs btn-success'
        = link_to 'Filter aufheben', reminders_path, class: 'btn btn-xs'

= boot_page_title do
  %h2 Erinnerungen

- if @reminders.present?
  %table#reminders_table.table.table-striped.table-condensed.table-hover.no-sidebar-actions
    %thead
      %tr
        %th Meeting vom
        %th Schüler/in
        %th Mentor
        %th Zweiter Mentor
        %th Empfänger
        %th Erstellt am
        %th Letzer Lernjournal Eintrag am
        %th Gesendet am
        %th Quittieren
    - @reminders.each do |reminder|
      %tr
        %td= human_date(reminder.held_at)
        %td= link_to reminder.kid.display_name, reminder.kid
        %td= link_to reminder.mentor.display_name, reminder.mentor
        %td
          -if reminder.secondary_mentor
            = link_to reminder.secondary_mentor.display_name, reminder.secondary_mentor
        %td= reminder.recipient
        %td= human_date(reminder.created_at.to_date)
        %td
          -if reminder.kid.last_journal_entry
            = link_to kid_path(reminder.kid, :anchor => 'journals') do
              = human_date(reminder.kid.last_journal_entry.held_at)
        %td
          - if reminder.sent_at
            = human_date(reminder.sent_at.to_date)
          - else
            = button_to "Zustellen", { action: "update", id: reminder.id }, method: :put, remote: true,  data: { disable_with: "In Arbeit..." }, class: 'btn btn-default btn-xs'
        %td
          = button_to "Quittieren", { action: "destroy", id: reminder.id }, method: :delete, remote: true,  data: { disable_with: "In Arbeit..." }, class: 'btn btn-default btn-xs'
- else
  %p Kein Eintrag vorhanden

app/views/reminders/update.js.erb
// When background submitted, the button receives the disabled flag
// After successful execution it gets removed from the dom
$('#reminders_table button:disabled').remove();