config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: { sessions: 'users/sessions' }

  resources :self_registrations, only: %i[create new] do
    collection do
      get 'success'
      get 'terms_of_use'
    end
  end

  root to: 'kids#index'
  resources :admins
  resources :documents
  resources :mentors do
    member do
      get 'edit_schedules'
      patch 'update_schedules'
      get 'disable_no_kids_reminder'
    end
  end
  resources :kids do
    resources :journals do
      resources :comments, only: %w[new create edit update]
    end
    resources :reviews
    resources :first_year_assessments
    resources :termination_assessments
    member do
      get 'edit_schedules'
      get 'show_kid_mentors_schedules'
      patch 'show_kid_mentors_schedules'
      patch 'update_schedules'
    end
  end
  resources :kid_mentor_relations do
    delete :destroy_all, on: :collection
  end
  resources :available_kids
  resources :schedules
  resources :schools
  resources :reminders
  resources :teachers
  resources :principals
  resource :site
  resources :substitutions do
    member do
      put 'inactivate'
    end
  end
  resources :mentor_matchings do
    member do
      put :accept
      put :decline
      put :confirm
    end
  end

  get '/lehrpersonen', to: redirect('/self_registrations/new?type=teacher')
  get '/mentoren', to: redirect('/self_registrations/new?type=mentor')

  get '/exception_test' => 'exception_test#error'
end

app/views/notifications/first_year_assessment_created.erb
Liebes Future Kids Team

Es wurde ein neues Auswertungsgespräch auf der Future Kids-Onlineplattform angelegt:

<p>
Schüler/in:
<%= @assessment.kid.display_name %>
</p>

<p>
Mentor/in:
<%= @assessment.mentor.display_name %>
</p>

<p>
Lehrperson:
<%= @assessment.teacher.display_name %>
</p>

<p>
Gespräch:
<%= @assessment.display_name %>
</p>

<p>
Link:
<%= kid_url(@assessment.kid)+"#first_year_assessment_#{@assessment.id}" %>
</p>

<p>
Datum:
<%= I18n.l(@assessment.held_at) if @assessment.held_at %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.development_teacher') %>
<%= @assessment.human_development_teacher %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.development_mentor') %>
<%= @assessment.human_development_mentor %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.goals_teacher') %>
<%= @assessment.human_goals_teacher %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.goals_mentor') %>
<%= @assessment.human_goals_mentor %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.relation_mentor') %>
<%= @assessment.human_relation_mentor %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.motivation') %>
<%= @assessment.human_motivation %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.collaboration') %>
<%= @assessment.human_collaboration %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.breaking_off') %>
<%= @assessment.breaking_off %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.breaking_reason') %>
<%= @assessment.human_breaking_reason %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.goal_1') %>
<%= @assessment.human_goal_1 %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.goal_2') %>
<%= @assessment.human_goal_2 %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.goal_3') %>
<%= @assessment.human_goal_3 %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.improvements') %>
<%= @assessment.human_improvements %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.note') %>
<%= @assessment.human_note %>
<p>

app/views/notifications/first_year_assessment_created.html.erb
Liebes Future Kids Team

Es wurde ein neues Auswertungsgespräch auf der Future Kids-Onlineplattform angelegt:

<p>
Schüler/in:
<%= @assessment.kid.display_name %>
</p>

<p>
Mentor/in:
<%= @assessment.mentor.display_name %>
</p>

<p>
Lehrperson:
<%= @assessment.teacher.display_name %>
</p>

<p>
Gespräch:
<%= @assessment.display_name %>
</p>

<p>
Link:
<%= kid_url(@assessment.kid)+"#first_year_assessment_#{@assessment.id}" %>
</p>

<p>
Datum:
<%= I18n.l(@assessment.held_at) if @assessment.held_at %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.development_teacher') %>
<%= @assessment.human_development_teacher %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.development_mentor') %>
<%= @assessment.human_development_mentor %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.goals_teacher') %>
<%= @assessment.human_goals_teacher %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.goals_mentor') %>
<%= @assessment.human_goals_mentor %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.relation_mentor') %>
<%= @assessment.human_relation_mentor %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.motivation') %>
<%= @assessment.human_motivation %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.collaboration') %>
<%= @assessment.human_collaboration %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.breaking_off') %>
<%= @assessment.breaking_off %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.breaking_reason') %>
<%= @assessment.human_breaking_reason %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.goal_1') %>
<%= @assessment.human_goal_1 %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.goal_2') %>
<%= @assessment.human_goal_2 %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.goal_3') %>
<%= @assessment.human_goal_3 %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.improvements') %>
<%= @assessment.human_improvements %>
</p>

<p>
<%= I18n.t('activerecord.attributes.first_year_assessment.note') %>
<%= @assessment.human_note %>
<p>

app/views/notifications/important_journal_created.erb
<p>
  Liebe pädagogische Coaches
</p>

<p>
  Es wurde ein neues Lernjournal auf der Future Kids-Onlineplattform angelegt:
</p>

<table>
  <tr>
    <th>
      Schüler/in:
    </th>
    <td>
      <%= @journal.kid.display_name %>
    </td>
  </tr>
  <tr>
    <th>
      Journal:
    </th>
    <td>
      <%= @journal.display_name %>
    </td>
  </tr>
  <tr>
    <th>
      Link:
    </th>
    <td>
      <%= kid_url(@journal.kid) + "#journal_#{@journal.id}" %>
    </td>
  </tr>
  <tr>
    <th>
      Datum:
    </th>
    <td>
      <%= I18n.l(@journal.held_at) if @journal.held_at %>
    </td>
  </tr>

  <%- unless @journal.cancelled? %>
    <tr>
      <th>
        Von:
      </th>
      <td>
        <%= @journal.human_start_at %>
      </td>
    </tr>
    <tr>
      <th>
        Bis:
      </th>
      <td>
        <%= @journal.human_end_at %>
      </td>
    </tr>

    <tr>
      <th>
        Lernziel:
      </th>
      <td>
        <%= simple_format(@journal.goal) %>
      </td>
    </tr>

    <tr>
      <th>
        Fach / Thema:
      </th>
      <td>
        <%= simple_format(@journal.subject) %>
      </td>
    </tr>

    <tr>
      <th>
        Beobachtungen und Vorgehensweise:
      </th>
      <td>
        <%= simple_format(@journal.method) %>
      </td>
    </tr>

    <tr>
      <th>
        Erfolge / Schwierigkeiten und Interpretation:
      </th>
      <td>
        <%= simple_format(@journal.outcome) %>
      </td>
    </tr>

    <tr>
      <th>
        Bemerkungen:
      </th>
      <td>
        <%= simple_format(@journal.note) %>
      </td>
    </tr>
  <%- end %>
</table>


<%- if @journal.cancelled? %>
  <p>
    <b>Treffen ausgefallen</b>
  </p>
<%- end %>

app/views/notifications/journals_created.html.erb
<p>
  Liebe Lehrperson
</p>

<p>
  Es wurden neue Lernjournale auf der Future Kids-Onlineplattform angelegt:
</p>

<%- @journals.each do |journal| %>
  <table>
    <tr>
      <th>
        Schüler/in:
      </th>
      <td>
        <%= journal.kid.display_name %>
      </td>
    </tr>
    <tr>
      <th>
        Journal:
      </th>
      <td>
        <%= journal.display_name %>
      </td>
    </tr>
    <tr>
      <th>
        Link:
      </th>
      <td>
        <%= kid_url(journal.kid) + "#journal_#{journal.id}" %>
      </td>
    </tr>
    <tr>
      <th>
        Datum:
      </th>
      <td>
        <%= I18n.l(journal.held_at) if journal.held_at %>
      </td>
    </tr>

    <%- unless journal.cancelled? %>
      <tr>
        <th>
          Von:
        </th>
        <td>
          <%= journal.human_start_at %>
        </td>
      </tr>
      <tr>
        <th>
          Bis:
        </th>
        <td>
          <%= journal.human_end_at %>
        </td>
      </tr>

      <tr>
        <th>
        Förderbereich:
        </th>
        <td>
          <%= simple_format(journal.goal) %>
        </td>
      </tr>

      <tr>
        <th>
          Fach / Thema:
        </th>
        <td>
          <%= simple_format(journal.subject) %>
        </td>
      </tr>

      <tr>
        <th>
          Beobachtungen und Vorgehensweise:
        </th>
        <td>
          <%= simple_format(journal.method) %>
        </td>
      </tr>

      <tr>
        <th>
          Erfolge / Schwierigkeiten und Interpretation:
        </th>
        <td>
          <%= simple_format(journal.outcome) %>
        </td>
      </tr>

      <tr>
        <th>
          Bemerkungen:
        </th>
        <td>
          <%= simple_format(journal.note) %>
        </td>
      </tr>
    <%- end %>
  </table>


  <%- if journal.cancelled? %>
    <p>
      <b>Treffen ausgefallen</b>
    </p>
  <%- end %>

<%- end %>

app/views/notifications/mentor_matching_confirmed.text.erb
Liebe Lehrperson

Der/die Mentor/in <%= @mentor_matching.mentor.display_name %> hat das Mentoring mit <%= @mentor_matching.kid.display_name %> definitiv übernommen.

app/views/notifications/mentor_matching_created.text.erb
Liebe/r Lehrer/in

Der/die Mentor/in <%= @mentor_matching.mentor.display_name %> hat ein Mentorat für <%= @mentor_matching.kid.display_name %> angefragt.
Sehen Sie hier das Profil des/der Mentor/in an und akzeptieren oder lehnen sie es ab: <%= mentor_matching_url(id: @mentor_matching.id) %>

<% if @mentor_matching.message.present? %>
  Nachricht der Mentor/in:
  <%= @mentor_matching.message %>
<% end %>

app/views/notifications/mentor_matching_declined.text.erb
Liebe/r Mentor/in

Deine Mentoringanfrage für das Kind in <%= @mentor_matching.kid.city %>, Klassenstufe <%= @mentor_matching.kid.grade %>,
<%= @mentor_matching.kid.human_sex %> wurde abgelehnt, die Lehrperson hat sich für eine/n andere/n Mentor/in entschieden.

Eine Liste der Schüler/innen ohne Mentorat kannst Du hier einsehen: <%= available_kids_url %>

app/views/notifications/mentor_matching_declined_by_mentor.text.erb
Liebe Lehrperson

Der/die Mentor/in <%= @mentor_matching.mentor.display_name %> hat die Mentoring Anfrage für <%= @mentor_matching.kid.display_name %> zurückgezogen.

app/views/notifications/remind.text.erb
Liebe Mentorin, Lieber Mentor

Uns ist aufgefallen, dass du fuer diese Woche noch keinen Lernjournal Eintrag
fuer <%= @reminder.kid.display_name %> vorgenommen hast.
Bitte hole dies innerhalb der nächsten 24 Stunden nach.

app/views/notifications/termination_assessment_created.erb
Liebes Future Kids Team

Es wurde ein neues Abschluss-Feedback auf der Future Kids-Onlineplattform angelegt:

<p>
  Schüler/in:
  <%= @assessment.kid.display_name %>
</p>

<p>
  Lehrperson:
  <%= @assessment.teacher.display_name %>
</p>

<p>
  Gespräch:
  <%= @assessment.display_name %>
</p>

<p>
  Link:
  <%= kid_url(@assessment.kid)+"#termination_assessment_#{@assessment.id}" %>
</p>

<p>
  Datum:
  <%= I18n.l(@assessment.held_at) if @assessment.held_at %>
</p>
<p>
<%= I18n.t('activerecord.attributes.termination_assessment.development') %>
<%= @assessment.human_development %>
</p>
<p>
<%= I18n.t('activerecord.attributes.termination_assessment.goals') %>
<%= @assessment.human_goals %>
</p>
<p>
<%= I18n.t('activerecord.attributes.termination_assessment.goals_reached') %>
<%= @assessment.human_goals_reached %>
</p>
<p>
<%= I18n.t('activerecord.attributes.termination_assessment.note') %>
<%= @assessment.human_note %>
</p>
<p>
<%= I18n.t('activerecord.attributes.termination_assessment.collaboration') %>
<%= @assessment.human_collaboration %>
</p>
<p>
<%= I18n.t('activerecord.attributes.termination_assessment.improvements') %>
<%= @assessment.human_improvements %>
</p>

app/views/notifications/termination_assessment_created.html.erb
Liebes Future Kids Team

Es wurde ein neues Abschluss-Feedback auf der Future Kids-Onlineplattform angelegt:

<p>
  Schüler/in:
  <%= @assessment.kid.display_name %>
</p>

<p>
  Lehrperson:
  <%= @assessment.teacher.display_name %>
</p>

<p>
  Gespräch:
  <%= @assessment.display_name %>
</p>

<p>
  Link:
  <%= kid_url(@assessment.kid)+"#termination_assessment_#{@assessment.id}" %>
</p>

<p>
  Datum:
  <%= I18n.l(@assessment.held_at) if @assessment.held_at %>
</p>
<p>
<%= I18n.t('activerecord.attributes.termination_assessment.development') %>
<%= @assessment.human_development %>
</p>
<p>
<%= I18n.t('activerecord.attributes.termination_assessment.goals') %>
<%= @assessment.human_goals %>
</p>
<p>
<%= I18n.t('activerecord.attributes.termination_assessment.goals_reached') %>
<%= @assessment.human_goals_reached %>
</p>
<p>
<%= I18n.t('activerecord.attributes.termination_assessment.note') %>
<%= @assessment.human_note %>
</p>
<p>
<%= I18n.t('activerecord.attributes.termination_assessment.collaboration') %>
<%= @assessment.human_collaboration %>
</p>
<p>
<%= I18n.t('activerecord.attributes.termination_assessment.improvements') %>
<%= @assessment.human_improvements %>
</p>

app/views/notifications/test.html.erb
<h1>Hallo</h1>
<p>
Dies ist das Testmail von Future Kids!
</p>

app/views/notifications/test.text.erb
Hallo

Dies ist das Testmail von Future Kids!

app/views/notifications/user_registered.haml
= t(".body", user_type: @user_type)
= link_to @user_link, @user_link